### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by airdine** [ArPIHomeSecurity/pywiegand#1]
Hello, 

Can you explain how to compile it to be able to use the same example in the README ?

Thanks for the share

Regards

**Comment by gkovacs81** [comment]
I use the library in my security system project. The environment on the Raspberry PI is prepared here:
https://github.com/ArPIHomeSecurity/arpi_management/blob/master/scripts/install_environment.sh#L146

You need the following lines:
```
echo "## Install wiringpi for pywiegand"
git clone $QUIET https://github.com/WiringPi/WiringPi.git ~/wiringpi
cd ~/wiringpi
./build
sudo ldconfig
```
