### ISSUE TITLE
Question - Library not working

### ISSUE THREAD

**Issue by simonxstark** [ArPIHomeSecurity/pywiegand#3]
Hey!
This Library would be perfect for a small Raspberry Pi Project i'm working on but i'm not able to make it work. 

I got this Error Message:
"File "/home/XXXXXXXXX/wiegandtest.py", line 1, in <module>
    from pywiegand import WiegandReader
  File "/home/XXXXXXXXXXX/.venv/lib/python3.9/site-packages/pywiegand/__init__.py", line 1, in <module>
    import pywiegand.extension.pywiegand_adapter as wa
ModuleNotFoundError: No module named 'pywiegand.extension.pywiegand_adapter'"

I am not a programmer but it seems that in the "__init__.py" file the "pywiegand_adapter.cpp" (?) doesnt get imported properly...
Is it because of the Python/Raspberry Version i'm using? Can i change anything to make it work?

I use Python 3.9.2 64-Bit on an Raspberry Pi 4 B 2GB and VS Code as an Development Environment (but i also installed the library directly on the raspberry pi and tried to run a test python programm with the terminal, there i got the same error message). I Imported the Library with pip and it also automatically installed wiringPi.

I hope someone can help me with that, i couldnt find any comparable alternatives to this library online.

**Comment by gkovacs81** [comment]
@simonxstark: I released a new version of the package with version 0.4.3.
(The problem was related to the poetry build changes.)
